name: Build & Test Contact Form Project

on:
  workflow_call:
    inputs:
      solution_path:
        description: Path to Project Solution File
        required: true
        type: string

jobs:
  build-test:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ${{ inputs.solution_path }}

      - name: Build
        run: dotnet build ${{ inputs.solution_path }} --configuration Release --no-restore

      - name: Test with Coverage
        run: |
          dotnet test ${{ inputs.solution_path }} --configuration Release --no-build --verbosity normal
