name: Terraform CI/CD

on:
  workflow_call:
    secrets:
      aws_identity_provider_role:
        description: "AWS Identity Provider Role"
        required: true
      aws_region:
        description: "AWS Region to Deploy"
        required: true
    inputs:
      run_deployment:
        description: "Terraform Apply to Deploy Changes"
        required: true
        default: false
        type: boolean
      run_destroy:
        description: "Terraform Destroy to Remove Changes"
        required: false
        default: false
        type: boolean
      tfvars_path:
        description: "Path to the tfvars file"
        required: true
        type: string
      TF_WORKING_DIR:
        description: "Terraform working directory"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Plan and Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws_identity_provider_role }}
          aws-region: ${{ secrets.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Logs Paths
        run: |
          echo ${{ inputs.TF_WORKING_DIR }}
          echo ${{ inputs.tfvars_path }}
          echo "List Current Directory"
          ls

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ inputs.TF_WORKING_DIR }}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ${{ inputs.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ inputs.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file="${{ inputs.tfvars_path }}"
        working-directory: ${{ inputs.TF_WORKING_DIR }}

      - name: Terraform Apply
        if: inputs.run_deployment
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ inputs.TF_WORKING_DIR }}

      - name: Terraform Destroy
        if: inputs.run_destroy
        run: terraform destroy -auto-approve tfplan
        working-directory: ${{ inputs.TF_WORKING_DIR }}
